let mapleader="\<Space>"
let maplocalleader="\\"

imap jk <Esc>

filetype indent plugin on
syntax on
set omnifunc=syntaxcomplete#Complete

call plug#begin('~/.vim/bundle')

Plug 'chriskempson/base16-vim'
Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
Plug 'Xuyuanp/nerdtree-git-plugin', {'on': 'NERDTreeToggle'}
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'itchyny/lightline.vim'
Plug 'wincent/command-t'
Plug 'christoomey/vim-tmux-navigator'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'lervag/vimtex', {'for': 'tex'}

call plug#end()


" tmux/split navigation
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <C-h> :TmuxNavigateLeft<CR>
nnoremap <silent> <C-j> :TmuxNavigateDown<CR>
nnoremap <silent> <C-k> :TmuxNavigateUp<CR>
nnoremap <silent> <C-l> :TmuxNavigateRight<CR>

let g:lightline = {
  \ 'colorscheme' : 'seoul256',
  \ 'separator': { 'left': '', 'right': '' },
  \ 'subseparator': { 'left': '', 'right': '' }
  \ }

let g:UltiSnipsExpandTrigger="<f5>"
let g:UltiSnipsEditSplit="vertical"
